import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Shield, ShieldCheck, Copy, Check, Clock } from "lucide-react";
import type { ZkProof } from "@shared/schema";
import { useState } from "react";

interface ZkProofCardProps {
  proof: ZkProof;
  agentName?: string;
}

function truncateProofData(data: string, maxLength: number = 64): string {
  if (data.length <= maxLength) return data;
  return `${data.slice(0, maxLength / 2)}...${data.slice(-maxLength / 2)}`;
}

export function ZkProofCard({ proof, agentName }: ZkProofCardProps) {
  const [copied, setCopied] = useState(false);

  const copyProofData = async () => {
    await navigator.clipboard.writeText(proof.proofData);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const createdAt = new Date(proof.createdAt);

  return (
    <Card
      className="relative overflow-visible backdrop-blur-xl border-border/50"
      data-testid={`card-zkproof-${proof.id}`}
    >
      <CardHeader className="flex flex-row items-start justify-between gap-4 space-y-0 pb-2">
        <div className="flex items-center gap-3">
          <div
            className={`h-10 w-10 rounded-full flex items-center justify-center ${
              proof.verified
                ? "bg-green-500/20"
                : "bg-yellow-500/20"
            }`}
          >
            {proof.verified ? (
              <ShieldCheck className="h-5 w-5 text-green-500" />
            ) : (
              <Shield className="h-5 w-5 text-yellow-500" />
            )}
          </div>
          <div className="flex flex-col min-w-0">
            <span className="font-semibold text-foreground capitalize">
              {proof.proofType.replace(/_/g, " ")} Proof
            </span>
            {agentName && (
              <span className="text-xs text-muted-foreground">
                Generated by {agentName}
              </span>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <Badge
            className={
              proof.verified
                ? "bg-green-500/20 text-green-500 dark:text-green-400"
                : "bg-yellow-500/20 text-yellow-600 dark:text-yellow-400"
            }
          >
            {proof.verified ? (
              <>
                <ShieldCheck className="h-3 w-3 mr-1" />
                Verified
              </>
            ) : (
              <>
                <Clock className="h-3 w-3 mr-1 animate-pulse" />
                Pending
              </>
            )}
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <p className="text-xs text-muted-foreground">Proof Data</p>
            <Button
              variant="ghost"
              size="sm"
              onClick={copyProofData}
              className="h-6 px-2"
              data-testid={`button-copy-proof-${proof.id}`}
            >
              {copied ? (
                <>
                  <Check className="h-3 w-3 mr-1 text-green-500" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="h-3 w-3 mr-1" />
                  Copy
                </>
              )}
            </Button>
          </div>
          <div className="p-3 rounded-md bg-muted/50 border border-border/50 overflow-hidden">
            <code className="text-xs font-mono text-muted-foreground break-all">
              {truncateProofData(proof.proofData)}
            </code>
          </div>
        </div>

        {proof.publicInputs && proof.publicInputs.length > 0 && (
          <div className="space-y-2">
            <p className="text-xs text-muted-foreground">Public Inputs</p>
            <div className="flex flex-wrap gap-2">
              {proof.publicInputs.slice(0, 5).map((input, index) => (
                <Badge key={index} variant="secondary" className="font-mono text-xs">
                  {typeof input === "string" && input.length > 16
                    ? `${input.slice(0, 8)}...${input.slice(-4)}`
                    : input}
                </Badge>
              ))}
              {proof.publicInputs.length > 5 && (
                <Badge variant="secondary" className="text-xs">
                  +{proof.publicInputs.length - 5} more
                </Badge>
              )}
            </div>
          </div>
        )}

        <div className="flex items-center justify-between pt-2 border-t border-border/50">
          <div className="flex items-center gap-4">
            {proof.verificationTime && (
              <div className="flex items-center gap-1 text-xs text-muted-foreground">
                <Clock className="h-3 w-3" />
                {proof.verificationTime}ms
              </div>
            )}
            {proof.transactionId && (
              <span className="text-xs text-muted-foreground">
                TX #{proof.transactionId}
              </span>
            )}
          </div>
          <span className="text-xs text-muted-foreground">
            {createdAt.toLocaleString()}
          </span>
        </div>

        <div className="flex items-center gap-2 p-2 rounded-md bg-primary/5 border border-primary/20">
          <Shield className="h-4 w-4 text-primary" />
          <span className="text-xs text-primary">
            Privacy preserved - Only succinct proof shared, no raw data exposed
          </span>
        </div>
      </CardContent>
    </Card>
  );
}
